
region_data = {
	"Menu": ["Harbourtown East", "Harbourtown Beach", "Night's Bridge Station"],
	"Harbourtown Beach": ["Harbourtown East", "Harbourtown Outskirts", "Brightside Pier"],
	"Harbourtown East": ["Harbourtown Beach"],
	"Harbourtown Outskirts": ["Upper Path", "New Wirral Park"],
	"Upper Path": ["Harbourtown West", "Thirstaton Lake", "Harbourtown Station"],
	"Harbourtown West": [],
	"New Wirral Park": ["Autumn Hill", "Eastham Woods", "Deadlands", "Lakeside", "Glowcester Road Station"],
	"Autumn Hill": ["Mourningtown", "Dino Quarry"],
	"Eastham Woods": ["Cherry Meadow", "NE Mire Sea", "Ham", "Eastham Woods Cliff"],
	"Eastham Woods Cliff": ["Falldown Mall"],
	"Deadlands": ["Deadlands Coast", "New London"],
	"Deadlands Coast": ["Southern Isles", "Dino Quarry"],
	"Dino Quarry": [],
	"New London": [],
	"NE Mire Sea": [],
	"Southern Isles": [],
	"Lakeside": ["Thirstaton Lake", "Cherry Meadow"],
	"Thirstaton Lake": ["Waterloop Station"],
	"Cherry Meadow": ["The Marshes", "Cast Iron Shore", "Mt Wirral", "Cherry Cross Station"],
	"Ham": ["Mt Wirral"],
	"The Marshes": ["Piper Farm", "Lost Hearts Graveyard", "West Mire Sea", "Spider Cave", "Landkeeper HQ"],
	"Spider Cave": [],
	"Piper Farm": ["Harbourtown West"],
	"Lost Hearts Graveyard": ["Aldgrave Tomb Station"],
	"West Mire Sea": [],
	"Cast Iron Shore": ["Titania Shipwreck"],
	"Mt Wirral": ["Brokenhead", "Icelington Station"],
	"Brokenhead": [],
	"Harbourtown Station": [],
	"Glowcester Road Station": [],
	"Mourningtown": ["Mourningstar Crescent Station"],
	"Mourningstar Crescent Station": [],
	"Falldown Mall": [],
	"Waterloop Station": [],
	"Cherry Cross Station": [],
	"Titania Shipwreck": ["Bard Street Station"],
	"Bard Street Station": [],
	"Landkeeper HQ": [],
	"Aldgrave Tomb Station": [],
	"Icelington Station": [],
	"Night's Bridge Station": ["Postgame"],
	"Postgame": [],
	"Brightside Pier": ["The Witch House", "Funworld", "Cosmic Zone"],
	"The Witch House": [],
	"Funworld": [],
	"Cosmic Zone": [],
}